{{- define "temporal.password-env" -}}
{{- $root := index . 0 -}}
{{- $store := index . 1 -}}
valueFrom:
  secretKeyRef:
    name: {{ default (include "temporal.componentname" (list $root (printf "%s-store" $store.name))) $store.config.existingSecret }}
    key: {{ default "password" $store.config.secretKey }}
{{- end -}}

{{- define "temporal.user-env" -}}
{{- $store := index . 1 -}}
valueFrom:
  secretKeyRef:
    name: {{ required (printf "Please specify existingSecret or userExistingSecret for %s store when userSecretKey is set" $store.name) (default $store.config.existingSecret $store.config.userExistingSecret) }}
    key: {{ $store.config.userSecretKey }}
{{- end -}}
