{{- if $.Values.admintools.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.componentname" (list $ "admintools") }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "admintools" "") | nindent 4 }}
spec:
  type: ClusterIP 
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh

  selector:
    app.kubernetes.io/name: {{ include "temporal.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admintools
{{- end }}
