{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-tls
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "TLS cert is required when tls.enabled=true" .Values.tls.cert | b64enc | quote }}
  tls.key: {{ required "TLS key is required when tls.enabled=true" .Values.tls.key | b64enc | quote }}
{{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc | quote }}
{{- end }}
{{- end }}
