{{- if $.Values.server.enabled }}
{{- range $service := (list "frontend" "internal-frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.server $service }}
{{- $replicaCount := $.Values.server.replicaCount }}
{{- if eq $replicaCount nil }}
{{- $replicaCount = 1 }}
{{- end }}
{{- if and (hasKey $serviceValues "replicaCount") (ne $serviceValues.replicaCount nil) }}
{{- $replicaCount = $serviceValues.replicaCount }}
{{- end }}
{{- if and $serviceValues.enabled (gt ($replicaCount | int) 0) ($serviceValues.podDisruptionBudget) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ include "temporal.kubernetesNamespace" $ }}
  name: {{ include "temporal.componentname" (list $ $service) }}-pdb
  labels:
    {{- include "temporal.resourceLabels" (list $ $service "") | nindent 4 }}
  {{- with include "temporal.resourceAnnotations" (list $ $service "pdb") }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $serviceValues.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "temporal.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $service }}
---
{{- end }}
{{- end }}
{{- end }}
