{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.serviceAccountName" $ }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "" "") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-10"
    {{- with .Values.serviceAccount.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}

{{- range $service := (list "frontend" "internal-frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.server $service }}
{{- $componentSA := dict }}
{{- if and (hasKey $serviceValues "serviceAccount") (kindIs "map" $serviceValues.serviceAccount) }}
  {{- $componentSA = $serviceValues.serviceAccount }}
{{- end }}
{{- if and (kindIs "map" $componentSA) (hasKey $componentSA "create") $componentSA.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.componentServiceAccountName" (list $ $service) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ $service "") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-10"
    {{- with $componentSA.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}

{{- range $component := (list "admintools" "web" "schema" "test") }}
{{- $componentValues := index $.Values $component }}
{{- $componentSA := dict }}
{{- if and (hasKey $componentValues "serviceAccount") (kindIs "map" $componentValues.serviceAccount) }}
  {{- $componentSA = $componentValues.serviceAccount }}
{{- end }}
{{- if and (kindIs "map" $componentSA) (hasKey $componentSA "create") $componentSA.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.componentServiceAccountName" (list $ $component) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ $component "") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-10"
    {{- with $componentSA.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}