{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "temporal.kubernetesNamespace" $ }}
  name: {{ include "temporal.serviceAccountName" $ }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "" "") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-10"
    {{- with .Values.serviceAccount.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}

{{- range $component := (list "frontend" "internal-frontend" "history" "matching" "worker" "admintools" "web" "schema" "test") }}
{{- $componentSA := include "temporal.componentServiceAccountConfig" (list $ $component) | fromYaml -}}
{{- if and (kindIs "map" $componentSA) (eq (default false $componentSA.create) true) (include "temporal.componentServiceAccountEnabled" (list $ $component) | trim | eq "true") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.componentServiceAccountName" (list $ $component) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ $component "") | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-10"
    {{- with $componentSA.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}