{{- range $_, $store := (include "temporal.persistence.eachStore" $ | fromYaml) }}
  {{- if empty $store.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.persistence.secretName" (list $ $store) }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "" "secret") | nindent 4 }}
  {{- if or $.Values.schema.useHelmHooks $.Values.server.secretAnnotations }}
  annotations:
    {{- if $.Values.schema.useHelmHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with $.Values.server.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  password: {{ default "" $store.config.password | b64enc | quote }}
---
  {{- end }}
{{- end }}
