{{- if $.Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "temporal.fullname" $ }}-dynamic-config"
  labels:
    {{- include "temporal.resourceLabels" (list $ "" "") | nindent 4 }}
data:
  dynamic_config.yaml: |-
  {{- if $.Values.server.dynamicConfig }}
    {{- toYaml .Values.server.dynamicConfig | nindent 4 }}
  {{- end }}
{{- end }}
