{{- if .Values.web.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "temporal.componentname" (list $ "web") }}
  labels:
    {{- include "temporal.resourceLabels" (list $ "web" "") | nindent 4 }}
    {{- with .Values.web.httpRoute.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.web.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.web.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.web.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.web.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "temporal.fullname" $ }}-web
          port: {{ $.Values.web.service.port }}
          weight: 1
      {{- end }}
{{- end }}