apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "temporal-proxy.fullname" . }}
  namespace: {{ include "temporal-proxy.namespace" . }}
  labels:
    {{- include "temporal-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ tpl (toYaml .Values.config) . | indent 4 }}
