prometheus:
  enabled: false
grafana:
  enabled: false
elasticsearch:
  enabled: false
schema:
  createDatabase:
    enabled: false

mysql:
  enabled: true
  auth:
    rootPassword: jeremias
  initdbScripts:
    init.sql: |
      CREATE DATABASE temporal;
      CREATE DATABASE temporal_visibility;
  commonAnnotations:
    "helm.sh/hook": "pre-install"

server:
  config:
    persistence:
        default:
          driver: "cassandra"
          cassandra:
            hosts: temporal-cassandra.temporal-tests.svc.cluster.local
            port: 9042
            keyspace: temporal
            user: cassandra
            password: cassandra
            consistency:
              default:
                consistency: local_quorum
                serialConsistency: local_serial
        visibility:
          driver: "sql"
          sql:
            driver: "mysql8"
            host: "temporal-mysql.temporal-tests.svc.cluster.local"
            port: 3306
            database: "temporal_visibility"
            user: "root"
            password: "jeremias"

cassandra:
  image:
    repository: bitnami/cassandra
    repo: bitnami/cassandra
    tag: 5.0.3-debian-12-r9
  dbUser:
    user: cassandra
    password: cassandra
    forcePassword: false
  initDB:
    initdb-create-keyspace.cql: |
      CREATE KEYSPACE IF NOT EXISTS temporal
      WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
