elasticsearch:
  enabled: false
cassandra:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
worker:
  keda:
    enabled: true
    pollingInterval: 30
    cooldownPeriod: 300
    initialCooldownPeriod: 0
    minReplicaCount: 0
    maxReplicaCount: 5
    triggers:
      - type: temporal
        metadata:
          namespace: default
          taskQueue: "workflow_with_single_noop_activity:test"
          targetQueueSize: "2"
          activationTargetQueueSize: "0"
          endpoint: temporal-frontend.temporal.svc.cluster.local:7233
          queueTypes: workflow
      - type: temporal
        metadata:
          namespace: default
          taskQueue: "workflow:test"
          targetQueueSize: "2"
          activationTargetQueueSize: "0"
          endpoint: temporal-frontend.temporal.svc.cluster.local:7233
