elasticsearch:
  enabled: false
cassandra:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
worker:
  keda:
    enabled: true
    pollingInterval: 30
    # -- Period (in seconds) to wait after the last trigger reported active before scaling the resource back to 0
    cooldownPeriod: 300
    # -- The delay (in seconds) before the `cooldownPeriod` starts after the initial creation of the `ScaledObject`.
    initialCooldownPeriod: 0
    # -- Minimum number of replicas KEDA will scale the resource down to.
    # By default, it’s scale to zero, but you can use it with some other value as well.
    minReplicaCount: 0
    # -- This setting is passed to the HPA definition that KEDA will create for a given resource and
    # holds the maximum number of replicas of the target resource.
    maxReplicaCount: 5
    fallback: {}
    # server.keda.fallback -- Defines a number of replicas to fall back to if a scaler is in an error state.
    # @raw
    # Example:
    # ```yaml
    # fallback:             # Optional. Section to specify fallback options
    #   failureThreshold: 3 # Mandatory if fallback section is included
    #   replicas: 6         # Mandatory if fallback section is included
    # ```
    advanced: {}
    # server.keda.advanced -- Specifies HPA related options
    # @raw
    # Example:
    # ```yaml
    # advanced:
    #   horizontalPodAutoscalerConfig:
    #     behavior:
    #       scaleDown:
    #         stabilizationWindowSeconds: 300
    #         policies:
    #           - type: Percent
    #             value: 100
    #             periodSeconds: 15
    # ```
    triggers:
    # server.keda.triggers -- List of triggers to activate scaling of the target resource
    # @raw
    # Example:
    # ```yaml
    # triggers:
      - type: temporal
        metadata:
          namespace: default
          taskQueue: "workflow_with_single_noop_activity:test"
          targetQueueSize: "2"
          activationTargetQueueSize: "0"
          endpoint: temporal-frontend.temporal.svc.cluster.local:7233
          queueTypes: workflow # optional
          buildId: 1.0.0 # optional
          selectAllActive: false # optional
          selectUnversioned: false optional
          minConnectTimeout: 5 # optional
          unsafeSsl: false # optional
      - type: temporal
        metadata:
          namespace: default
          taskQueue: "workflow:test"
          targetQueueSize: "2"
          activationTargetQueueSize: "0"
          endpoint: temporal-frontend.temporal.svc.cluster.local:7233
          queueTypes: workflow # optional
          buildId: 1.0.0 # optional
          selectAllActive: false # optional
          selectUnversioned: false optional
          minConnectTimeout: 5 # optional
          unsafeSsl: false # optional
    # ```
    annotations: {}
    # server.keda.annotations -- Annotations to apply to the ScaledObject CRD.
    # @raw
    # Example:
    # ```yaml
    # annotations:
    #   autoscaling.keda.sh/paused-replicas: "0"
    #   autoscaling.keda.sh/paused: "true"
    # ```
