server:
  frontend:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi

  history:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi

  matching:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi

  worker:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
