apiVersion: v2
name: temporal-proxy
description: The Temporal proxy handles routing between clusters, namespace translation, encryption, and more.
icon: https://raw.githubusercontent.com/temporalio/temporal-proxy/refs/heads/main/temporal-proxy-small.png

type: application
version: 0.1.0-alpha1
appVersion: v0.1.0-alpha.20260716

keywords:
  - temporal
  - workflow
  - orchestration
  - proxy
maintainers:
  - name: temporalio
    url: https://temporal.io/
home: https://github.com/temporalio/temporal-proxy
sources:
  - https://github.com/temporalio/temporal-proxy
